version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: expense_db
      DB_USER: postgres
      DB_PASSWORD: postgrespass
      SECRET_KEY: "change_this_secret"
      DEBUG: "True"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["./entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
