apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-expenses-backend
  labels:
    app: split-expenses
spec:
  replicas: 3
  selector:
    matchLabels:
      app: split-expenses
  template:
    metadata:
      labels:
        app: split-expenses
    spec:
      containers:
        - name: backend
          image: split-expenses-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@postgres-service:5432/split_expenses"
            - name: DEBUG
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: regcred