apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    route:
      receiver: default
    receivers:
      - name: default
        email_configs:
          - to: admin@example.com
